[theme]
# Color principal para elementos interactivos (botones, etc.)
primaryColor="#FFFF00"

# Color de fondo principal de la aplicaci√≥n
backgroundColor="#000000"

# Color de fondo para elementos como la barra lateral o formularios
secondaryBackgroundColor="#31333F"

# Color del texto principal
textColor="#FFFF00"

# Fuente a utilizar
font="sans serif"
